# Site settings
title: 小胖的博客
email: wj940096538@163.com
description: 搭个自己的小博客,给自己一个瞎BB的地方
baseurl: ""
url: "http://littlepang.github.io"
github_username:  littlePang
paginate: 2

# Build settings
markdown: kramdown
excerpt_separator: "\n\n\n"

# Plugins
gems: [jekyll-paginate]
