# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 小胖的博客 
email: wj940096538@163.com
description: 搭个自己的小博客,给自己一个瞎BB的地方
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://littlepang.github.io" # the base hostname & protocol for your site
github_username:  littlePang

# Build settings
markdown: kramdown
